return {
    {
        "williamboman/mason.nvim"
    },
    {
        "neovim/nvim-lspconfig"
    },
    {
        "williamboman/mason-lspconfig.nvim"
    },
    {
        "VonHeikemen/lsp-zero.nvim"
    },
    {
        "hrsh7th/nvim-cmp"
    },
    {
        "folke/neodev.nvim"
    },
    {'hrsh7th/nvim-cmp'},
    {'hrsh7th/cmp-nvim-lsp'},
    {'L3MON4D3/LuaSnip'},
}
