require("presence").setup({
    auto_update         = true,
    neovim_image_text   = "neowowowovim :3",
    main_image          = "neovim",
    client_id           = "793271441293967371",
    log_level           = nil,
    debounce_timeout    = 10,
    enable_line_number  = false,
    blacklist           = {},
    buttons             = true,
    file_assets         = {},
    show_time           = true,

    editing_text        = "you're awesome btw <3",
    file_explorer_text  = "neovim nya~",
    git_commit_text     = "git push --force :3",
    plugin_manager_text = "<3",
    reading_text        = "am rtfming :3",
    workspace_text      = ">~<",
    line_number_text    = "Line %s out of %s",
})
